services:
  postgres:
    container_name: StudentsWPF
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "StudentsDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

volumes:
  postgres-data: